apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: brianpolanco-com-tls
spec:
  secretName: brianpolanco-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: brianpolanco.com
  dnsNames:
    - brianpolanco.com
    - www.brianpolanco.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - brianpolanco.com
          - www.brianpolanco.com
